[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "/"

  # Directory that contains the deploy-ready static files after build
  publish = "out"

  # Default build command.
  command = "bun install --legacy-peer-deps && npm run generate-metadata && bun run build"

[build.environment]
  # Disable Netlify Next.js plugin
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SKIP_LINT = "true"
  NEXT_TYPESCRIPT_CHECK = "false"
  NEXT_DISABLE_TYPESCRIPT_CHECK = "true"
  NEXT_IGNORE_TYPESCRIPT_ERRORS = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SKIP_ESLINT_CHECK = "true"
  SKIP_TYPE_CHECK = "true"

# Explicitly define custom headers for specific files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/about.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/contact.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/privacy.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/articles.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/first-article.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = [
    "https://github.com/**",
    "https://ext.same-assets.com/**",
    "https://ugc.same-assets.com/**",
    "https://cdn.jsdelivr.net/**",
    "https://unpkg.com/**",
    "https://tessdata.projectnaptha.com/**"
  ]
