[build]
  command = "bash netlify-build.sh"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_STANDALONE = "true"
  NEXT_SKIP_LINT = "true"
  NEXT_TYPESCRIPT_CHECK = "false"
  NEXT_DISABLE_TYPESCRIPT_CHECK = "true"
  NEXT_IGNORE_TYPESCRIPT_ERRORS = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  node_bundler = "esbuild"
  included_files = ["**/.next/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = [
    "https://github.com/**",
    "https://ext.same-assets.com/**",
    "https://ugc.same-assets.com/**",
    "https://cdn.jsdelivr.net/**",
    "https://unpkg.com/**",
    "https://tessdata.projectnaptha.com/**"
  ]
