name: Deploy to Netlify

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          export NEXT_TELEMETRY_DISABLED=1
          export NEXT_SKIP_LINT=true
          export NEXT_TYPESCRIPT_CHECK=false
          export NEXT_DISABLE_TYPESCRIPT_CHECK=true
          export NEXT_IGNORE_TYPESCRIPT_ERRORS=true
          npm run build

      - name: Add headers file
        run: |
          echo -e "/*\n  Content-Security-Policy: default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; style-src * 'unsafe-inline'; font-src * 'unsafe-inline'\n  X-Frame-Options: DENY\n  X-XSS-Protection: 1; mode=block" > out/_headers
          echo -e '[[headers]]\n  for = \"/*\"\n  [headers.values]\n    Content-Security-Policy = \"default-src * '\''unsafe-inline'\'' '\''unsafe-eval'\''; script-src * '\''unsafe-inline'\'' '\''unsafe-eval'\''; connect-src * '\''unsafe-inline'\''; img-src * data: blob: '\''unsafe-inline'\''; style-src * '\''unsafe-inline'\''; font-src * '\''unsafe-inline'\'';\"\n    X-Frame-Options = \"DENY\"\n    X-XSS-Protection = \"1; mode=block\"' > out/netlify.toml

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './out'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
